hpc <- read.table('household_power_consumption.txt',header=TRUE,sep=";",stringsAsFactors=FALSE)
hpc$Global_active_power<-as.numeric(as.character(hpc$Global_active_power))
groundhog<-subset(hpc, Date == "1/2/2007" | Date == "2/2/2007")
groundhog$Timestamp <- strptime(with(groundhog,paste(Date, Time)), format="%d/%m/%Y %R:%S")
png('plot3.png', width = 480, height = 480, units = "px")
with(groundhog, plot(Timestamp, Sub_metering_1, type='l', xlab='', ylab='Energy sub metering'))
with(groundhog, lines(Timestamp, Sub_metering_2, col='red'))
with(groundhog, lines(Timestamp, Sub_metering_3,col='blue'))
legend('topright', legend = c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'), col = c('black', 'red', 'blue'), lwd=1 )
dev.off()
