hpc <- read.table('household_power_consumption.txt',header=TRUE,sep=";",stringsAsFactors=FALSE)
hpc$Global_active_power<-as.numeric(as.character(hpc$Global_active_power))
groundhog<-subset(hpc, Date == "1/2/2007" | Date == "2/2/2007")
png('plot1.png', width = 480, height = 480, units = "px")
hist(groundhog$Global_active_power, main="Global Active Power", xlab="Global Active Power (kilowatts)", ylab='Frequency', col="red")
dev.off()
