hpc <- read.table('household_power_consumption.txt',header=TRUE,sep=";",stringsAsFactors=FALSE)
hpc$Global_active_power<-as.numeric(as.character(hpc$Global_active_power))
groundhog<-subset(hpc, Date == "1/2/2007" | Date == "2/2/2007")
groundhog$Timestamp <- strptime(with(groundhog,paste(Date, Time)), format="%d/%m/%Y %R:%S")
png('plot2.png', width = 480, height = 480, units = "px")
with(groundhog, plot(Timestamp, Global_active_power, type='l', xlab='', ylab='Global Active Power (kilowatts)'))
dev.off()
